name: CI 
on:
  push:
    branches: [ master ]
  pull_request:
jobs:   
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Check Branch
      run: echo "${{ env.branch }}"

    - name: Get Hash
      id: hash
      run: echo "git_hash=$(git rev-parse --short "$GITHUB_SHA")" 

    - name: Check Hash
      run: echo "${{ env.hash }}"
