name: CI 
on:
  push:
    branches: [ master ]
  pull_request:
jobs:   
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Check Branch
      run: echo "${{ github.head_ref }} "
